#!/bin/bash

SQLSERVER2MYSQL_VERSION=0

# Uses long options and modern getopt.  Validate this assumption
getopt -T 2>/dev/null
case $? in
4 ) ;; # Good - see getopt(1)
* ) echo "$0: Wrong getopt, sorry" >&2 ; exit 4 ;;
esac

function version()
{
    echo "SQLSERVER2MYSQL $SQLSERVER2MYSQL_VERSION"
}

function usage()
{
    echo "usage: $0 [-dhv][--debug|--help|--verbose|--version]"
}

function help()
{
    usage
    cat <<EOH  # TODO: Format flags based on screen dimensions
  -d|--debug  More helpful output
  -h|--help  Print help and exit
  -v|--verbose  Explain processing
  --version  Print version and exit

EOH
    version
    cat <<EOH
Report bugs to: "B. K. Oxley (binkley)" <binkley@alumni.rice.edu>
SQLSERVER2MYSQL home page: <https://github.com/binkley/sql-server2mysql>
EOH
}

shopt -s nocasematch

debug=false
verbose=false

args=$(getopt -n "$0" -l debug,help,verbose,version -o dhv -s bash -- "$@") || exit $?
set - $args

while getopts :dhv-: opt
do
    case "$opt" in
    d ) debug=true ;;
    h ) help ; exit 0 ;;
    v ) verbose=true ;;
    - ) case $OPTARG in
        debug ) debug=true ;;
        help ) help ; exit 0 ;;
        verbose ) verbose=true ;;
        version ) version ; exit 0 ;;
        * ) usage >&2 ; exit 2 ;;
        esac ;;
    * ) usage >&2 ; exit 2 ;;
    esac
done
shift $((OPTIND - 1))

if $debug
then
    export PS4='$0:$LINENO+ '
    set -x
fi

go_directive_re='^( *)GO *$'
set_directive_re='^( *)(SET +[^@].*)'
create_proc_re='^ *CREATE +PROCEDURE +.*'
create_proc_end='^( *)AS *$'
in_create_proc=false
local_var_re='^( *)SET +@'
temp_table_re='^( *)CREATE +TABLE +#(.*)'
temp_table_end='^ *\) *$'  # TODO: What if ) is on previous line?
in_temp_table=false

let lineno=0
while IFS='' read line
do
    let ++lineno
    line="${line/--/-- }"  # --Comment -> -- Comment
    line="${line//[/}"  # [some].[id] -> some.id
    line="${line//]/}"

    if [[ "$line" =~ $go_directive_re ]]
    then
        line="${BASH_REMATCH[1]};"  # GO -> ;
    elif [[ "$line" =~ $set_directive_re ]]
    then
        line="${BASH_REMATCH[1]}-- ${BASH_REMATCH[2]}"  # SET FOO ON -> -- SET FOO ON
    elif [[ "$line" =~ $create_proc_re ]]
    then
        line="$line("  # DECLARE PROCEDURE bob -> DECLARE PROCEDURE bob(
        in_create_proc=true
    elif [[ "$line" =~ $create_proc_end ]]
    then
	line="${BASH_REMATCH[1]})"  # AS -> ) for stored procedure params
        in_create_proc=false
    elif $in_create_proc
    then
        line="${line/@/IN }"  # @SomeParam AS CHAR(1) -> IN SomeParam CHAR(1)
        line="${line/ AS/}"
    elif [[ "$line" =~ $local_var_re ]]
    then
        line="$line;"
    elif [[ "$line" =~ $temp_table_re ]]
    then
        line="${BASH_REMATCH[1]}CREATE TEMPORARY TABLE ${BASH_REMATCH[2]}"
        in_temp_table=true
    elif $in_temp_table && [[ "$line" =~ $temp_table_end ]]
    then
        line="$line;"
        in_temp_table=false
    fi

    echo "$line -- l#$lineno"
done
