#!/bin/bash

set -e

fixed="$(./sql-server2mysql <<EOS
--No space
EOS
)"

test "$fixed" = "-- No space"

/bin/false

fixed="$(./sql-server2mysql <<EOS
  prefix --No space
EOS
)"

test "$fixed" = "  prefix -- No space"
